-- ============================================================================
-- LAB : "De l'avis client brut au dashboard IA — Pipeline retail automatisé"
-- MODULE 0 : SETUP
-- Durée : 10 min
-- ============================================================================

CREATE WAREHOUSE IF NOT EXISTS LAB_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE LAB_WH;
CREATE DATABASE IF NOT EXISTS LAB_RETAIL_AI;
USE DATABASE LAB_RETAIL_AI;

-- ─── Architecture Medallion : Bronze → Silver → Gold ───
CREATE SCHEMA IF NOT EXISTS BRONZE;   -- Données brutes telles qu'elles arrivent
CREATE SCHEMA IF NOT EXISTS SILVER;   -- Nettoyées, enrichies par l'IA
CREATE SCHEMA IF NOT EXISTS GOLD;     -- Agrégées, prêtes pour le business

-- ─── Stage pour le chargement ───
CREATE OR REPLACE STAGE BRONZE.LAB_STAGE
    FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 NULL_IF=(''));

-- ─── BRONZE : Tables sources brutes ───

CREATE OR REPLACE TABLE BRONZE.REVIEWS (
    REVIEW_ID VARCHAR,
    REVIEW_TEXT VARCHAR,
    RATING INT,
    VERIFIED_PURCHASE BOOLEAN
);

CREATE OR REPLACE TABLE BRONZE.GOOGLE_TRENDS (
    KEYWORD VARCHAR,
    AVG_INTEREST FLOAT,
    CURRENT_INTEREST INT,
    PEAK_INTEREST INT,
    TREND_DIRECTION VARCHAR
);

CREATE OR REPLACE TABLE BRONZE.PRODUCT_CATEGORIES (
    PRODUCT_KEYWORD VARCHAR,
    CATEGORY VARCHAR,
    SUBCATEGORY VARCHAR,
    GOOGLE_TREND_KEYWORD VARCHAR,
    PRICE_RANGE VARCHAR
);

-- ─── Chargement des 3 fichiers CSV ───
-- INSTRUCTION : Uploader les 3 CSV via Snowsight > Data > Add Data > Load files into BRONZE.LAB_STAGE

COPY INTO BRONZE.REVIEWS FROM @BRONZE.LAB_STAGE/reviews.csv
    FILE_FORMAT=(TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';
COPY INTO BRONZE.GOOGLE_TRENDS FROM @BRONZE.LAB_STAGE/google_trends.csv
    FILE_FORMAT=(TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';
COPY INTO BRONZE.PRODUCT_CATEGORIES FROM @BRONZE.LAB_STAGE/product_categories.csv
    FILE_FORMAT=(TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

-- Vérification
SELECT 'BRONZE.REVIEWS' AS TABLE_NAME, COUNT(*) AS NB_ROWS FROM BRONZE.REVIEWS
UNION ALL SELECT 'BRONZE.GOOGLE_TRENDS', COUNT(*) FROM BRONZE.GOOGLE_TRENDS
UNION ALL SELECT 'BRONZE.PRODUCT_CATEGORIES', COUNT(*) FROM BRONZE.PRODUCT_CATEGORIES;
